# Keeps the versions of the actions used in the workflow up to date by opening pull requests.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
